WEBSITE_MOTEL/Areas/Admin/Controllers/DUYETCTController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using WEBSITE_MOTEL.Models;
using System.Net;

namespace WEBSITE_MOTEL.Areas.Admin.Controllers
{
    public class DUYETCTController : Controller
    {
        // GET: Admin/DUYETCT
        TimNhaTroDataContext data = new TimNhaTroDataContext();
        public ActionResult CTApprove(int? page, string strSearch)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return Redirect("~/Admin/Home/Login");
            }
            ViewData["strSearch"] = strSearch;

            int iSize = 5;
            int iPageNum = (page ?? 1);
            if (!string.IsNullOrEmpty(strSearch))
            {
                var ct = (from a in data.TAIKHOANs
                          join b in data.CHUTROs on a.Id equals b.Id_TaiKhoan
                          join c in data.ANH_CCCDs on a.Id equals c.IdTaiKhoan
                          where b.TrangThai == 0
                          select new TaiKhoan()
                          {
                              sId = a.Id,
                              sTaiKhoanCT = a.TaiKhoan,
                              sMatKhauCT = a.MatKhau,
                              sHotenCT = a.HoTen,
                              sCCCD = a.CCCD,
                              sDiaChi = a.DiaChi,
                              sTrangThai = (int)b.TrangThai,
                              sEmailCT = a.Email,
                              sNgaySinh = (DateTime)a.NgaySinh,
                              sSDTCT = a.SDT,
                              sidcardphoto = c.IdCardPhoto,
                              sidcardphoto2 = c.IdCardPhoto2,
                          });
                return View(ct.OrderByDescending(n => n.sTrangThai == 0).ToPagedList(iPageNum, iSize));
            }
            else
            {
                var ct = (from a in data.TAIKHOANs
                          join b in data.CHUTROs on a.Id equals b.Id_TaiKhoan
                          join c in data.ANH_CCCDs on a.Id equals c.IdTaiKhoan
                          where b.TrangThai == 0
                          select new TaiKhoan()
                          {
                              sId = a.Id,
                              sTaiKhoanCT = a.TaiKhoan,
                              sMatKhauCT = a.MatKhau,
                              sHotenCT = a.HoTen,
                              sCCCD = a.CCCD,
                              sDiaChi = a.DiaChi,
                              sTrangThai = (int)b.TrangThai,
                              sEmailCT = a.Email,
                              sNgaySinh = (DateTime)a.NgaySinh,
                              sSDTCT = a.SDT,
                              sidcardphoto = c.IdCardPhoto,
                              sidcardphoto2 = c.IdCardPhoto2,
                          });
                return View(ct.OrderByDescending(n => n.sTrangThai == 0).ToPagedList(iPageNum, iSize));
            }
        }
        public void SendEmail(string emailpost)
        {
            // Tạo đối tượng SmtpClient với thông tin cấu hình
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
            smtpClient.EnableSsl = true;
            smtpClient.Credentials = new NetworkCredential("luongminhtam0710@gmail.com", "minhtam710");

            // Tạo đối tượng MailMessage với thông tin người gửi và người nhận
            MailMessage mailMessage = new MailMessage();
            mailMessage.From = new MailAddress("luongminhtam0710@gmail.com");
            mailMessage.To.Add("recipient@example.com");
            mailMessage.Subject = "Subject of the email";
            mailMessage.Body = "Body of the email";

            // Gửi email
            smtpClient.Send(mailMessage);
        }
        public ActionResult DuyetCT(int id)
        {
            CHUTRO CT = data.CHUTROs.FirstOrDefault(p => p.TrangThai == 0);
            TAIKHOAN tk = data.TAIKHOANs.Where(n => n.Id == id).FirstOrDefault();
            if (CT != null)
            {
                CT.TrangThai = 1;
                data.SubmitChanges();
                //string senderEmail = "luongminhtam0710@gmail@minhtam710.com";
                //string senderPassword = "minhtam710";
                //string receiverEmail = tk.Email;
                //string subject = "Admin duyệt bài";
                //string body = "Tài khoản của bạn đã được duyệt. Bây giờ bạn có thể vào trang web với tư cách chủ trọ." +
                //    "Trân trọng.";

                //bool isEmailSent = EmailHelper.SendEmail(senderEmail, senderPassword, receiverEmail, subject, body);
                //if (isEmailSent)
                //{
                //    // Gửi thành công, thực hiện các hành động khác nếu cần
                //    ViewBag.Message = "Email sent successfully.";
                //}
                //else
                //{
                //    // Gửi thất bại, xử lý lỗi nếu có
                //    ViewBag.Error = "Error sending email.";
                //}

                //TempData["Message"] = "Duyệt thành công!";
            }
            return RedirectToAction("CTApprove");

        }
        public ActionResult BoDuyetCT(int id)
        {
            var anhcccd = data.ANH_CCCDs.Where(p => p.IdTaiKhoan == id);
            data.ANH_CCCDs.DeleteAllOnSubmit(anhcccd);
            data.SubmitChanges();
            var chutros = data.CHUTROs.Where(p => p.Id_TaiKhoan == id);
            data.CHUTROs.DeleteAllOnSubmit(chutros);
            data.SubmitChanges();
            var tk = data.TAIKHOANs.SingleOrDefault(p => p.Id == id);
            if (tk != null)
            {
                data.TAIKHOANs.DeleteOnSubmit(tk);
                data.SubmitChanges();
                ViewBag.ThongBao = "Xóa tài khoản thành công";
            }
            return RedirectToAction("CTApprove");
        }
    }
}

WEBSITE_MOTEL/Areas/Admin/Views/DUYETCT/CTApprove.cshtml
@model IEnumerable<WEBSITE_MOTEL.Models.TaiKhoan>
@using WEBSITE_MOTEL.Models
@using PagedList.Mvc;
@{
    ViewBag.Title = "CTApprove";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}

<h2>Danh sách các chủ trọ chưa được duyệt</h2>
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("CTApprove", "DUYETCT", FormMethod.Get, new { @class = "navbar-form navbar-left", @role = "search" }))
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" name="strSearch" value="@ViewData["strSearch"]" placeholder="Tìm kiếm">
                        </div>
                    }

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Tài khoản</th>
                                <th>Mật khẩu</th>
                                <th>Họ tên</th>
                                <th>Email</th>
                                <th>SĐT</th>
                                <th>Số CCCD</th>
                                <th>Ảnh CCCD(Mặt trước)</th>
                                <th>Ảnh CCCD(Mặt sau)</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sTaiKhoanCT)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sMatKhauCT)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sHotenCT)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sEmailCT)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sSDTCT)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sCCCD)
                                    </td>
                                    <td>
                                        <div class="item active">
                                            <div class="image-container">
                                                <img src="~/images/@item.sidcardphoto" alt="anh1" class="zoomable-image" style="width: 145px; height: 110px; border-radius:5%;">
                                                <div class="zoomed-image"></div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="item">
                                            <div class="image-container">
                                                <img src="~/images/@item.sidcardphoto2" alt="anh2" class="zoomable-image" style="width: 145px; height: 110px; border-radius:5%;">
                                                <div class="zoomed-image"></div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("DuyetCT", new { id = item.sId })" class="btn btn-success" role="button">Duyệt</a> |
                                        <a href="@Url.Action("BoDuyetCT", new { id = item.sId })" class="btn btn-danger" role="button">Từ Chối</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // Sự kiện click nút "Duyệt Phòng"
        $(".table").on("click", "#st3", function () {
            var id = $(this).data("id");
            $.ajax({
                url: "/DUYETCT/DuyetCT",
                type: "POST",
                data: { id: id },
                success: function (result) {
                    // Hiển thị thông báo
                    alert("Đã Duyệt thành công");
                    // Reload trang để cập nhật lại danh sách phòng trọ
                    window.location.reload();
                },
                error: function () {
                    // Hiển thị thông báo lỗi
                    alert("Duyệt Phòng không thành công!");
                }
            });
        });


        $(".table").on("click", "#st4", function () {
            var id = $(this).data("id");
            if (confirm("Bạn có chắc chắn muốn xóa tài khoản này không?")) {
                $.ajax({
                    url: "/DUYETCT/BoDuyetCT",
                    type: "POST",
                    data: { id: id },
                    success: function (result) {
                        // Hiển thị thông báo
                        alert("Đã bỏ duyệt tài khoản thành công");
                        // Reload trang để cập nhật lại danh sách phòng trọ
                        window.location.reload();
                    },
                    error: function () {
                        // Hiển thị thông báo lỗi
                        alert("Bỏ duyệt tài khoản không thành công!");
                    }
                });
            }
        });
    });
</script>
<style>
    .image-container {
        position: relative;
        display: inline-block;
    }

    .zoomable-image {
        width: 300px;
        height: 200px;
        border-radius: 5%;
    }

    .zoomed-image {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.7);
        display: none;
    }

    .zoomable-image:hover + .zoomed-image {
        display: block;
    }
</style>

<script>
    $(document).ready(function () {
        $(".zoomable-image").mousemove(function (e) {
            var $zoomedImage = $(this).siblings(".zoomed-image");
            var imageWidth = $(this).width();
            var imageHeight = $(this).height();
            var mouseX = e.pageX - $(this).offset().left;
            var mouseY = e.pageY - $(this).offset().top;
            var zoomX = (mouseX / imageWidth) * 100;
            var zoomY = (mouseY / imageHeight) * 100;
            $zoomedImage.css({
                "background-image": "url(" + $(this).attr("src") + ")",
                "background-position": zoomX + "% " + zoomY + "%"
            });
        });
    });
</script>