WEBSITE_MOTEL/Areas/Admin/Controllers/QLDUYETPHONGController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEBSITE_MOTEL.Models;

namespace WEBSITE_MOTEL.Areas.Admin.Controllers
{
    public class QLDUYETPHONGController : Controller
    {
        TimNhaTroDataContext data = new TimNhaTroDataContext();
        // GET: Admin/QLDUYETPHONG
        public ActionResult RoomApprove(int? page, string strSearch)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return Redirect("~/Admin/Home/Login");
            }
            ViewData["strSearch"] = strSearch;

            int iSize = 5;
            int iPageNum = (page ?? 1);

            var query = from a in data.BAIDANGs
                        join b in data.CHUTROs on a.Id_ChuTro equals b.Id
                        join c in data.IMAGEs on a.Id equals c.Id_PhongTro
                        join e in data.TAIKHOANs on b.Id_TaiKhoan equals e.Id
                        where a.TrangThai == 4
                        select new RoomDetail()
                        {
                            sMa = a.Id,
                            sTenPhong = a.TenPhong,
                            sHoTen = e.HoTen,
                            sDienTich = (int)a.DienTich,
                            sSoluong = (int)a.SoLuong,
                            sAnhBia = a.AnhBia,
                            sMoTa = a.MoTa,
                            dNgayCapNhat = (DateTime)a.Ngay,
                            dGiaCa = (double)a.GiaCa,
                            sSDT = e.SDT,
                            sEmail = e.Email,
                            sUrl_Path = c.Url_Path,
                            sUrl_Path2 = c.Url_Path2,
                            sUrl_Path3 = c.Url_Path3,
                            sUrl_Path4 = c.Url_Path4,
                            sDiaChi = a.Diachi,
                            sDien = (double)a.Dien,
                            sNuoc = (double)a.Nuoc,
                            sGuiXe = (double)a.GuiXe,
                            sInternet = (double)a.Internet,
                            sDoiTuong = (byte)a.Doituong,
                            sTrangThai = (byte)a.TrangThai,
                            sTenKV = a.KhuVuc
                        };

            return View(query.OrderByDescending(n => n.sTrangThai == 4).ToPagedList(iPageNum, iSize));
        }

        [HttpPost]
        public ActionResult RoomApprove()
        {
            BAIDANG phong = data.BAIDANGs.FirstOrDefault(p => p.TrangThai == 4);

            if (phong == null)
            {
                return HttpNotFound();
            }

            return View(phong);
        }

        public ActionResult DuyetPhong(int id)
        {
            BAIDANG phong = data.BAIDANGs.FirstOrDefault(p => p.Id == id && p.TrangThai == 4);

            if (phong != null)
            {
                phong.TrangThai = 1;
                data.SubmitChanges();
                TempData["Message"] = "Duyệt phòng thành công!";
            }

            return RedirectToAction("RoomApprove");
        }

        public ActionResult TuChoiPhong(int id)
        {
            var phong = data.BAIDANGs.SingleOrDefault(p => p.Id == id);

            if (phong != null)
            {
                // Xóa phòng được từ chối khỏi bảng BAIDANG_DUYET
                data.BAIDANGs.DeleteOnSubmit(phong);
                data.SubmitChanges();
                ViewBag.ThongBao = "Từ chối phòng thành công";
            }

            return RedirectToAction("RoomApprove");
        }
    }
}

WEBSITE_MOTEL/Areas/Admin/Views/QLDUYETPHONG/RoomApprove.cshtml
@using WEBSITE_MOTEL.Models
@using PagedList.Mvc;
@model PagedList.PagedList<WEBSITE_MOTEL.Models.RoomDetail>
@{
    ViewBag.Title = "RoomApprove";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}


<h2>Danh sách các phòng trọ chưa được duyệt</h2>
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("RoomApprove", "QLDUYETPHONG", FormMethod.Get, new { @class = "navbar-form navbar-left", @role = "search" }))
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" name="strSearch" value="@ViewData["strSearch"]" placeholder="Tìm kiếm">
                        </div>

                    }

                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Tên chủ trọ
                                </th>
                                <th>
                                    Tên phòng
                                </th>
                                <th>
                                    Mô tả
                                </th>
                                <th>
                                    Diện tích
                                </th>
                                <th>
                                    Số lượng
                                </th>
                                <th>
                                    Giá
                                </th>
                                <th>
                                    Diện tích
                                </th>
                                <th>
                                    Địa chỉ
                                </th>
                                <th>
                                    Ảnh bìa
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sHoTen)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sTenPhong)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sMoTa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sDienTich)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sSoluong)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.dGiaCa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sDienTich)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sDiaChi)
                                    </td>
                                    <td>
                                        <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
                                            <div class="carousel-inner">
                                                <div class="carousel-item active">
                                                    <img src="~/images/@item.sAnhBia" class="d-block w-100" alt="Image 1" style="width: 200px; height: 110px; border-radius:5%;">
                                                </div>
                                                <div class="carousel-item">
                                                    <img src="~/images/@item.sUrl_Path" class="d-block w-100" alt="Image 2" style="width: 145px; height: 110px; border-radius:5%;">
                                                </div>
                                                <div class="carousel-item">
                                                    <img src="~/images/@item.sUrl_Path2" class="d-block w-100" alt="Image 3" style="width: 145px; height: 110px; border-radius:5%;">
                                                </div>
                                                <div class="carousel-item">
                                                    <img src="~/images/@item.sUrl_Path3" class="d-block w-100" alt="Image 4" style="width: 145px; height: 110px; border-radius:5%;">
                                                </div>
                                                <div class="carousel-item">
                                                    <img src="~/images/@item.sUrl_Path4" class="d-block w-100" alt="Image 5" style="width: 145px; height: 110px; border-radius:5%;">
                                                </div>
                                            </div>
                                            <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                                                <span class="carousel-control-prev-icon" style="background-color:black;" aria-hidden="false"></span>

                                            </button>
                                            <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                                                <span class="carousel-control-next-icon" style="background-color:black;" aria-hidden="true"></span>
                                            </button>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("DuyetPhong", new { id = item.sMa })" class="btn btn-success" role="button">Duyệt</a> |
                                        <a href="@Url.Action("TuChoiPhong", new { id = item.sMa })" class="btn btn-danger" role="button">Từ Chối</a>
                                    </td>
                                    
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.left-arrow').click(function () {
            $('#myCarousel').carousel('prev');
        });

        $('.right-arrow').click(function () {
            $('#myCarousel').carousel('next');
        });
    });
</script>