WEBSITE_MOTEL/Areas/Admin/Controllers/HoTroController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using OfficeOpenXml;
using System.Web.UI;
using WEBSITE_MOTEL.Models;

namespace WEBSITE_MOTEL.Areas.Admin.Controllers
{
    public class HoTroController : Controller
    {
        TimNhaTroDataContext data = new TimNhaTroDataContext();
        // GET: Admin/HoTro
        [HttpGet]
        public ActionResult Index(int? page, string strSearch)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return Redirect("~/Admin/Home/Login");
            }
            ViewData["strSearch"] = strSearch;
            
            int iSize = 5;
            int iPageNum = (page ?? 1);
            return View(data.HOTROs.OrderBy(n=>n.Id).ToPagedList(iPageNum, iSize));
        }
        public ActionResult XoaHoTro(int id)
        {
            try
            {
                var hotro = data.HOTROs.SingleOrDefault(p => p.Id == id);
                if (hotro != null)
                {
                    data.HOTROs.DeleteOnSubmit(hotro);
                    data.SubmitChanges();
                    TempData["ThongBao"] = "Xóa thành công";
                }
                else
                {
                    TempData["ThongBao"] = "Không tìm thấy thông tin hỗ trợ";
                }
            }
            catch (Exception ex)
            {
                TempData["ThongBao"] = "Xóa thất bại. Lỗi: " + ex.Message;
            }

            return RedirectToAction("Index");
        }
        public ActionResult ExportExcel()
        {
            // Lấy dữ liệu cần xuất ra Excel từ database
            TimNhaTroDataContext db = new TimNhaTroDataContext();
            var hotros = db.HOTROs.ToList();

            // Tạo một file Excel mới
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add("Danh sách hỗ trợ");
            worksheet.Cells["B1"].Value = "DANH SÁCH CÁC VẤN ĐỀ CẦN ĐƯỢC HỖ TRỢ ";
            // Định dạng font chữ
            worksheet.Cells["A2:C2"].Style.Font.Bold = true;

            // Định dạng ô đầu tiên thành màu xám
            worksheet.Cells["A2"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
            worksheet.Cells["A2"].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Gray);
            worksheet.Cells["B2"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
            worksheet.Cells["B2"].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Gray);
            worksheet.Cells["C2"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
            worksheet.Cells["C2"].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Gray);

            // Căn giữa dòng tiêu đề
            worksheet.Cells["A2:C2"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;

            // Thiết lập định dạng tiêu đề cột
            worksheet.Column(1).Width = 20;
            worksheet.Column(2).Width = 50;
            worksheet.Column(3).Width = 20;
            worksheet.Cells["A2"].Value = "Họ tên";
            worksheet.Cells["B2"].Value = "Mô tả";
            worksheet.Cells["C2"].Value = "Số điện thoại";

            // Thêm dữ liệu vào các ô
            var row = 3;
            foreach (var hotro in hotros)
            {
                worksheet.Cells[row, 1].Value = hotro.Ten;
                worksheet.Cells[row, 2].Value = hotro.MotaVande;
                worksheet.Cells[row, 3].Value = hotro.Sdt;
                row++;
            }

            // Lưu file Excel vào bộ nhớ đệm
            var stream = new MemoryStream();
            package.SaveAs(stream);

            // Trả về file Excel dưới dạng download
            stream.Position = 0;
            var fileName = "DanhSachHoTro.xlsx";
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }

    }
}

WEBSITE_MOTEL/Areas/Admin/Views/HoTro/Index.cshtml
@using WEBSITE_MOTEL.Models
@using PagedList.Mvc;
@model PagedList.PagedList<WEBSITE_MOTEL.Models.HOTRO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}

<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">

                <div class="table-responsive">
                    @using (Html.BeginForm("Index", "HoTro", FormMethod.Get, new { @class = "navbar-form navbar-left", @role = "search" }))
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" name="strSearch" value="@ViewData["strSearch"]" placeholder="Tìm kiếm">
                        </div>
                    }
                    <table class="table">
                        <tr>
                            <th style="text-align:center">
                                Họ tên
                            </th>
                            <th style="text-align:center">
                                Số điện thoại
                            </th>
                            <th style="text-align:center">
                                Mô tả
                            </th>
                            <th style="text-align:right">
                                Hành động
                            </th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ten)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sdt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MotaVande)
                                </td>
                                <td style="text-align:right">

                                   @* <a href="@Url.Action("ChiTiet", new { id = item.Id })" class="btn btn-success" role="button">Duyệt</a> *@|
                                    <a href="@Url.Action("XoaHoTro", new { id = item.Id })" class="btn btn-danger" role="button" onclick="return confirm('Bạn có chắc chắn muốn xóa hỗ trợ này không?')">Xóa</a>
                                </td>
                            </tr>
                        }
                    </table>
                    <div style="text-align: right;">
                        <a href="@Url.Action("ExportExcel", "HoTro")" class="btn btn-primary">Xuất Excel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="alertContainer">
            @if (!string.IsNullOrEmpty(TempData["ThongBao"] as string))
            {
                <div class="alert alert-success">
                    @TempData["ThongBao"]
                </div>
            }
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#alertContainer").fadeOut("slow");
        }, 5000); // 5 giây
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
    </div>
</div>

<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
</style>